### ISSUE TITLE
Is the verkle tree easy for prunning old state?

### ISSUE THREAD

**Issue by cifer76** [gballet/go-verkle#232]
Thanks for the excellent work @gballet.

I have just learned the minimal proof size the verkle tree will bring to us, but I'm in concern of another question: is it prunning friendly?

As we known, geth is fighting with state prunning issue for a long time, it's hard for the merkle patricia tree to find out the stale nodes and clean them up. Will the verkle tree be facing this issue either?

**Comment by gballet** [comment]
Verkle trees will mostly face the same issue, yes. They benefit from two mitigating effects, though:

 1. The tree takes less space in RAM, so flushing will be more infrequent. This means that stale nodes have a higher chance of being pruned before they are flushed to disk
 2. They have less internal nodes, so running the pruning command should take less time

Overall, though, the difficulty of pruning in geth is a consequence of the key format that we chose to store data in the db. We are in the process of changing the key format, so that pruning will become much easier. This change will also apply to verkle trees.
