### ISSUE TITLE
What does HashNode have a `hash` field?

### ISSUE THREAD

**Issue by GrapeBaBa** [gballet/go-verkle#258]
```go
type HashedNode struct {
	hash       *Fr
	commitment *Point
}
```
In current code base, actually serializing and parsing node are just using `commitment`, what is the purpose for `hash`?

**Comment by gballet** [comment]
Hash is used to cache the serialization when needed. I don't think it's used in too many places anymore, but its presence makes sense because calculating the serialization of a commitment is quite expensive. I expect it will be used again when optimization becomes a topic, assuming we keep the same serialization algorithm.
