### ISSUE TITLE
use a pool for polynomial allocations

### ISSUE THREAD

**Issue by gballet** [gballet/go-verkle#64]
In the new version of `LeafNodes`, an array of values needs to be allocated each time a new last-level node is created.

```go
values:     make([][]byte, n.treeConfig.nodeWidth),
```

 In the case of `InsertOrdered`, a performance gain could be realized by reusing a pool of nodes. This also works for `children` in `InternalNode`.

**Comment by muddlebee** [comment]
@gballet hello 👋   I am participating in [Ethereum's Core Developer Apprenticeship Program](https://blog.ethereum.org/2021/09/06/core-dev-apprenticeship-second-cohort/) which runs through February 2022. I

 wanted to pick this issue and work on understanding the go-implementation of verkle trees. Do you have any specific timeline for this issue? So I can pick it up and work accordingly? If this is fine by you?

**Comment by muddlebee** [comment]
So according to my proposal for Developer Apprenticeship Program  I wanted to pick a few issues from the go-verkle implementation and make an attempt to fix it by understanding the code. I believe go-verkle will soon be merged into the go-ethereum codebase. Any specific timelines? 

So that I can make an attempt to contribute something meaningful to this project.

**Comment by gballet** [comment]
Sure, you can pick this issue if you want.

**Comment by gballet** [comment]
no longer needed, closing
